### ISSUE TITLE
No issue, only a smile!

### ISSUE THREAD

**Issue by ghost** [notetau/addon-minimal-digital-clock#1]
Hi,

Running flawlessly _Minimal Digital Clock_ 1.0 / Firefox 63.0.1 (x64) / Windows 7 (x64)
Using the extension's toolbar button's badge to display the time is smart!
I've managed to save even more space by adding a few lines of dedicated code in my userChrome.css in order to have the time badge displayed right under the browser's buttonbox, just the right size/place!

![sans titre 1](https://user-images.githubusercontent.com/42912760/48302157-0368f580-e4f9-11e8-8c4a-b6c8086f6bc5.jpg)

Thanks!

**Comment by notetau** [comment]
Cool! Thank you!
